@startuml
scale 600 width
hide empty description

state "Autonomous Driving System" as AutonomousDrivingSystem
state AutonomousDrivingSystem {
    state "MIAV Startup" as MIAVStartup
    state "MIAV Shutdown" as MIAVShutdown
    state "MIAV Reboot" as MIAVReboot
    state "MIAV Software Update" as MIAVSoftwareUpdate
    state "Map Update" as MapUpdate
    state "Log Collection" as LogCollection
    state "Autonomous Mission" as AutonomousMission #YellowGreen

}


[*] -right-> MIAVStartup : Turn on the vehicle
MIAVStartup -right-> AutonomousMission : Boot System
MIAVStartup --> MapUpdate : Check Map is\nInvalid
MIAVStartup --> MIAVSoftwareUpdate : Check Software is\nOut-of-date
MapUpdate --> MIAVReboot : Complete
MIAVSoftwareUpdate --> MIAVReboot : Complete
MIAVReboot -right-> AutonomousMission : Start Operation
AutonomousMission -left-> MIAVReboot : Reboot System
AutonomousMission --> MIAVShutdown : Finish the\nOperation
MIAVShutdown -left-> LogCollection : Collect Data Storage System
LogCollection --> [*] : Update Logs

@enduml
