@startuml
hide empty description
skinparam backgroundColor #FFFFFF
skinparam state {
  BackgroundColor #DDF0E1
  BorderColor #009688
  FontSize 12
  FontColor #333333
}

/' Define states in the Autonomous Driving Operation '/
state "Autonomous Driving Operation" as AutonomousDrivingOperation {

     state "Arriving Drop Off Point" as ArrivingDropOffPoint #C8E6C9
     state "Operation Start" as OperationStart #C8E6C9
     state "Travel Cancellation" as TravelCancellation #FFCDD2
     state "Picking Up Passengers" as PickingUpPassengers #C8E6C9
     state "Dropping Off Passengers" as DroppingOffPassengers #C8E6C9
     state "Departure Notice" as DepartureNotice #C8E6C9
     state "Departure from Pick Up Point" as DepartureFromPickUpPoint #C8E6C9
     state "Arrival Notice" as ArrivalNotice #C8E6C9

    state "Autonomous Driving" as AutonomousDriving #B2DFDB {
        state "Driving Pause" as DrivingPause #FFCDD2
        state "Temporary Manual Driving" as TemporaryManualDriving #FFCDD2

        state c <<choice>> 
        [*] --> c
        c --> DrivingPause : Approach pause\n position
        DrivingPause --> c : Continue driving
        c --> TemporaryManualDriving : Override
        TemporaryManualDriving --> c : Switch drive mode\n to autonomous
        c --> [*]
    }
}

/' Transitions and flow of operations '/
[*] -down-> OperationStart : Set drive mode to autonomous
OperationStart -down-> PickingUpPassengers : Start execution of desired route
PickingUpPassengers -right-> DepartureNotice : Inform passengers for departure
DepartureNotice -left-> PickingUpPassengers : Finish passenger notice
PickingUpPassengers -down-> DepartureFromPickUpPoint : Depart
DepartureFromPickUpPoint -down-> AutonomousDriving : Start autonomous driving
AutonomousDriving -up-> ArrivalNotice : Inform passengers\n for arrival
ArrivalNotice -down-> AutonomousDriving : Finish passenger\n notice
AutonomousDriving -up-> ArrivingDropOffPoint : Arrive at destination
ArrivingDropOffPoint -up-> DroppingOffPassengers : Arrive at destination
DroppingOffPassengers -left-> [*] : Set pick up location
DroppingOffPassengers -right-> TravelCancellation : Cancel Schedule
PickingUpPassengers -left-> TravelCancellation : Cancel schedule
TravelCancellation -left-> [*] : Terminate Operation
AutonomousDriving --> [*] : Monitor system health
AutonomousDriving --> [*] : Operator override
AutonomousDriving --> [*] : Emergency Stop

@enduml
